[project]
name = "cartpolistan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium[classic-control]>=1.2.1",
    "numpy>=2.3.4",
    "torch>=2.9.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.2",
]
